#!/bin/bash

while true
do
    echo -e "\n1.Create File 2.Display 3.Insert 4.Search 5.Modify 6.Delete 7.Exit"
    echo -n "Enter choice: "
    read ch

    case $ch in

    1)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo "File already exists"
        else
            touch "$fname"
            echo "File created successfully"
        fi
        ;;

    2)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo "Train Records:"
            cat "$fname"
        else
            echo "File does not exist"
        fi
        ;;

    3)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo -n "Enter Train Number: "
            read tno

            grep -w "$tno" "$fname" >/dev/null

            if [ $? -eq 0 ]; then
                echo "Train already exists"
            else
                echo -n "Enter Train Name: "
                read tname
                echo "$tno $tname" >> "$fname"
                echo "Train record inserted"
            fi
        else
            echo "File does not exist"
        fi
        ;;

    4)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo -n "Enter Train Number to search: "
            read tno

            grep -w "$tno" "$fname"

            if [ $? -eq 0 ]; then
                echo "Record found"
            else
                echo "Record not found"
            fi
        else
            echo "File does not exist"
        fi
        ;;

    5)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo -n "Enter Train Number to modify: "
            read tno

            grep -w "$tno" "$fname" >/dev/null

            if [ $? -eq 0 ]; then
                echo -n "Enter New Train Number and Name: "
                read ntno ntname

                grep -w "$ntno" "$fname" >/dev/null

                if [ $? -eq 0 ]; then
                    echo "New Train Number already exists"
                else
                    grep -vw "$tno" "$fname" > temp
                    echo "$ntno $ntname" >> temp
                    mv temp "$fname"
                    echo "Record modified successfully"
                fi
            else
                echo "Record not found"
            fi
        else
            echo "File does not exist"
        fi
        ;;

    6)
        echo -n "Enter file name: "
        read fname

        if [ -e "$fname" ]; then
            echo -n "Enter Train Number to delete: "
            read tno

            grep -w "$tno" "$fname" >/dev/null

            if [ $? -eq 0 ]; then
                grep -vw "$tno" "$fname" > temp
                mv temp "$fname"
                echo "Record deleted successfully"
            else
                echo "Record not found"
            fi
        else
            echo "File does not exist"
        fi
        ;;

    7)
        echo "Exiting..."
        exit 0
        ;;

    *)
        echo "Invalid choice"
        ;;
    esac

done